### ISSUE TITLE
No such file or directory in outlier detection

### ISSUE THREAD

**Issue by christopher-schroeder** [bahlolab/superSTR#16]
Hello

I call superstr in the following way

`superstr-outliers.py --pathogenic -i results/superstr/multiparse/fame_rna --bootstrapCI -is -m results/superstr/manifests/fame_rna.tsv --min_len 30 --max_len 101 > results/superstr/outlier/fame_rna.tsv 2> logs/superstr/outlier/fame_rna.log`

and I get an error message:

Traceback (most recent call last):
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/bin/superstr-outliers.py", line 211, in <module>
    df = pd.read_csv(file)
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/vol/huge/depienne/fame_rna/dna-seq-strling/.snakemake/conda/0914eb68a5b449325434937342b34375/lib/python3.10/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'results/superstr/multiparse/fame_rna/motifs/12mers/CCCCGCCCCGCG.csv'

Its correct, this specific file haven't been created and doesn't exist. If I invoke the outlier script without --pathogenic it works.

**Comment by lfearnley** [comment]
Sorry about the delayed reply here. This is a fairly quick fix and I'll try and push it through later today.
